# Generated by Django 2.1.1 on 2018-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_user',
            field=models.CharField(default='0.0.0.0', max_length=255),
            preserve_default=False,
        ),
    ]
